const  { makeExecutableSchema } = require('graphql-tools')

const typeDefinitions = `
type Abandons {
    abandonEndDate: String
    abandonStartDate: String
    commentJustifiedAbsence: String
    isJustified: Boolean
  }
  
  type TrainingSessions {
    name: String
    abandons: [Abandons]
  }
  
  type Trainees {
    birthdate: String
    email: String
    firstname: String
    handicaped: Boolean
    lastDiploma: String
    lastname: String
    nationality: String
    phone: String
    roadAddress: String
    status: String
    trainingSessions: [TrainingSessions]
  }
  
  type Data {
    trainees: [Trainees]
  }
  
  type AutogeneratedMainType {
    data: Data
  }`


const resolvers = {
  Query: {
    trainees: async () => {
        let res = fetch('https://app.digiforma.com/api/v1/graphiql', {
                method: 'POST',
              headers: { Authorization: "Bearer " + accessToken,
                        'Content-Type': 'application/json' },
                        body: JSON.stringify({ query:`query {
                          trainees{
                  lastname
                  firstname
                  trainingSessions {
                    name
                    abandons {
                      abandonStartDate
                      abandonEndDate
                      isJustified
                      commentJustifiedAbsence
                    }
            
                  }
                  nationality
                  birthdate
                  email
                  roadAddress
                  phone
                  lastDiploma
                  status
                  handicaped
            
                }
            
              }` 
              }),
            })
        res = JSON.parse(res);
        console.log(res);
        return res;
       }
}
}